# Generated by Django 5.1.3 on 2024-12-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryId', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('ItemId', models.AutoField(primary_key=True, serialize=False)),
                ('ItemName', models.CharField(max_length=500)),
                ('ItemDescription', models.CharField(max_length=500)),
                ('ItemPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ItemCategory', models.CharField(max_length=500)),
                ('ItemImage', models.CharField(max_length=500)),
                ('ItemStock', models.IntegerField()),
            ],
        ),
    ]
